# Generated by Django 3.0.5 on 2020-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUITestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=50)),
                ('casename', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=25)),
                ('resultwanted', models.CharField(max_length=1000)),
                ('resultinfact', models.CharField(max_length=1000)),
                ('testresult', models.CharField(max_length=10)),
                ('costtime', models.CharField(max_length=10)),
                ('log', models.TextField()),
                ('report', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('logname', models.CharField(max_length=20)),
                ('recordtime', models.CharField(max_length=25)),
                ('data', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=50)),
                ('single', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=10)),
                ('package', models.CharField(max_length=25)),
                ('testcase', models.CharField(max_length=25)),
                ('server', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('show', models.CharField(max_length=1)),
                ('executetime', models.CharField(max_length=25)),
            ],
        ),
    ]
