# Generated by Django 3.0.2 on 2020-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SERIALNUMBER', models.CharField(max_length=100)),
                ('GAME', models.CharField(max_length=100)),
                ('INSTALL', models.CharField(max_length=100)),
                ('ACTIVITY', models.CharField(max_length=100)),
                ('LEVEL', models.CharField(max_length=100)),
                ('RESULT', models.CharField(max_length=100)),
                ('LOG', models.CharField(max_length=19999)),
                ('REPORT', models.CharField(max_length=100)),
                ('EXECUTOR', models.CharField(max_length=100)),
            ],
        ),
    ]
