# Generated by Django 3.0.5 on 2020-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouitestresult',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='autouitestresult',
            name='log',
            field=models.TextField(),
        ),
    ]
